### ISSUE TITLE
Use xi-unicode for language agnostic line breaking

### ISSUE THREAD

**Issue by ishitatsuyuki** [alexheretic/gfx-glyph#1]
xi-unicode is a crate that implements Unicode line breaking standards. Line breaking by space has limits (mostly on Asian languages), so we should use a well standardized implementation instead.

**Comment by alexheretic** [comment]
Good idea, I'll look into it.

**Comment by alexheretic** [comment]
For version **0.2** I've replaced my previous trait responsible for this with `LineBreaker` and added a default implementation `StandardLineBreaker` which is backed by the xi-unicode iterator.

So now the default line break logic is UAX#14, whilst it can be custom implemented if desired.

Please re-open if the implementation seems no good!
