### ISSUE TITLE
Transition to gfx-hal

### ISSUE THREAD

**Issue by torkleyy** [alexheretic/gfx-glyph#10]
Hey @alexheretic, we at Amethyst are interested in using this crate for our text rendering. The features and the efficiency of `gfx-glyph` are great!

There's one concern we have though: with the new `gfx-hal`, how is this project going to continue?

**Comment by alexheretic** [comment]
Once a new `gfx` release is out with the new unified shader stuff I'll adapt `gfx_glyph`. I'll probably maintain a OpenGL version in the same way the gfx guys choose to maintain `0.16`.

While the new gfx glue will take a little work, the actual _good stuff_ that this crate provides should translate to any graphic API.

**Comment by Rhuagh** [comment]
Agreed, the gfx parts are quite simple and shouldn't be a whole lot of work to port.

**Comment by Rhuagh** [comment]
And the shader don't have to change at all, you just need to compile it to spir-v :)

**Comment by alexheretic** [comment]
I'm going to close this as it doesn't currently make sense to work on this. Once the new gfx is released we can re-open, or otherwise start porting.

**Comment by alexheretic** [comment]
In case anyone digs this issue up in regards to gfx-glyph gfx-hal support, my current plan is **not** to transition gfx-glyph to this any time soon. Instead glyph-brush provides most of the goodness without a render-api allegiance, and so of course can be used with gfx-hal.
