### ISSUE TITLE
Cannot render partial glyphs

### ISSUE THREAD

**Issue by Xaeroxe** [alexheretic/gfx-glyph#15]
When programming a single line text input box if the text gets wider than the box the text will need to scroll to the cursor.  This isn't possible right now with gfx_glyph, because if the text is wider than the box being rendered in sometimes an entire word just doesn't get rendered.  Basically I want the rendered box to be treated as a "window" to a line of text, with everything outside the window being invisible, but otherwise laid out and treated the same.

I'll be investigating this more closely myself if you don't get to this issue within about a month or two.  I have other priorities for a little bit but I do want to get back to this.

**Comment by alexheretic** [comment]
The built in layouts won't let you do this, but try  instead using a custom `GlyphPositioner` layout.

This allows you to provide two things
- generation of positioned glyphs
- the position of the draw bounds

You could use the single line built-in layout to handle lining up the glyphs, then calculate your window as the bounds rect. Partially out-of-bounds glyphs will be cut off in the correct aspect ratio.

There's an example of using a custom layout in the _performance_ example.

**Comment by Xaeroxe** [comment]
Thanks!
