### ISSUE TITLE
Most recent release (0.8.3) breaks semver

### ISSUE THREAD

**Issue by Rhuagh** [alexheretic/gfx-glyph#18]
The latest release bumps the rusttype dependency from 0.3 to 0.4, which cause all released projects that depend on 0.8.X of gfx_glyph and any version of rusttype to no longer build.

Please consider yanking 0.8.3 and republish it as 0.9.

**Comment by Rhuagh** [comment]
Thanks.

**Comment by alexheretic** [comment]
Yep thanks, I thought I could get away with it at the time as gfx-glyph wasn't susceptible to the reason rusttype was bumped. But with all the exported types we really need to follow rusttype & gfx semver for any reason.
