### ISSUE TITLE
Missing glyphs

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/gfx-glyph#2]
Tracker for dylanede/rusttype#52.

This can currently be worked around by replacing rusttype with the dylanede/rusttype#53 code. To do so add the following to your Cargo.toml:
```toml
[replace]
# Missing glyph bug awaiting fix in main rusttype repo, see https://github.com/dylanede/rusttype/issues/52
"rusttype:0.2.1" = { git = "https://github.com/alexheretic/rusttype", branch = "fix-glyph-not-cached" }
```

**Comment by alteous** [comment]
Unfortunately `rusttype` seems to be no longer maintaned. I suggest to make a fork of the crate and publish a new one with the patches. `gfx-glyph-backend`, `gfx-glyph-rasterizer`,  or`gfx-glyph-internals` might be suitable names.

**Comment by vitvakatu** [comment]
I agree with @alteous 
Thank you for your crate, by the way

**Comment by alexheretic** [comment]
`gfx_glyph:0.3.2` now has my fixed fork of `rusttype::gpu_cache` included. The workaround is no longer required.
