### ISSUE TITLE
Make it possible to add more fonts to an existing GlyphBrush

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/gfx-glyph#24]
It's not terribly necessary, but it would make some parts of the ggez integration in https://github.com/ggez/ggez/issues/132 nicer to deal with.  I rummaged around the `gfx_glyph` code a bit and didn't see a particular reason it couldn't be done; did I miss something?  If you okay this I'll happily make a PR.

Dynamic removal might be nice too just for the sake of symmetry, but is less important.

**Comment by alexheretic** [comment]
Generally I tried to minimise outward mutability, it makes reasoning with caches easier. But just adding new fonts and returning the new distinct font id seems like it should be fine; equivalent to adding them on construction and using them later.

I can probably add this tomorrow.

**Comment by icefoxen** [comment]
That's sensible, and thank you!

**Comment by alexheretic** [comment]
I've added the following
```rust
impl GlyphBrush {
    fn add_font_bytes<'a: 'font, B: Into<SharedBytes<'a>>>(&mut self, font_data: B) -> FontId;
    fn add_font<'a: 'font>(&mut self, font_data: Font<'a>) -> FontId;
}
```

@Ratysz @icefoxen Can you guys make sure this is useful to you, then I'll make a release later today.

**Comment by icefoxen** [comment]
Actually since removing a font would have to go down all the way to the
rusttype texture cache... Then yes, removing a font would basically be the
same as ditching the cache and making a new one anyway.
