### ISSUE TITLE
How can I make it works with PistonWindow 

### ISSUE THREAD

**Issue by Petan1996** [alexheretic/gfx-glyph#27]
Hello everyone,
i tried to use gfx-glyph with Piston and it does show only black screen without text.
I have proper font in folder with program. Os : windows 10.

Thank you for your reply.
I apologize for my english. Its not my native language.

    use piston_window::*;
    use gfx_glyph::{Section, GlyphBrushBuilder};

    fn main() {
    let mut window: PistonWindow = WindowSettings::new("App", [640, 480])
        .exit_on_esc(true)
        .opengl(OpenGL::V3_2)
        .build()
        .unwrap_or_else(|e| { panic!("Failed to build PistonWindow: {}", e) });

    let consola: &[u8] = include_bytes!("consola.ttf");
    let mut glyph_brush = GlyphBrushBuilder::using_font_bytes(consola)
        .initial_cache_size((256, 256))
        .build(window.factory.clone());

    let section = Section {
        text: "Hello All",
        screen_position: (10.0 , 10.0),
        color: [0.1, 0.9, 0.1, 1.0],
        ..Section::default()
    };

    while let Some(e) = window.next() {

        window.draw_2d(&e, |c, g| {
            clear([0.0, 0.0, 0.0, 1.0], g);   
        });

        glyph_brush.queue(section);

        glyph_brush.draw_queued(&mut window.encoder, &window.output_color,
                                                 &window.output_stencil).expect("draw");
 
    }
    }

**Comment by alexheretic** [comment]
It looks like if you use the `window.encoder` in Piston you have to flush it yourself.

```rust
...
glyph_brush
    .draw_queued(
        &mut window.encoder,
        &window.output_color,
        &window.output_stencil,
    )
    .expect("draw");

window.encoder.flush(&mut window.device);
```

**Comment by Petan1996** [comment]
That makes sense. Thank you. It works now.
