### ISSUE TITLE
Request: Add make versions of `draw_queued_with_transform` and friends that operate on raw render targets.

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/gfx-glyph#29]
It seems that dealing with gfx's raw types is basically necessary if you want to select color formats and such at runtime, so.

**Comment by alexheretic** [comment]
Yes that seems reasonable, I think I can support it without additional functions.

**Comment by icefoxen** [comment]
Looks nice to me!  Give me a day or so to try the branch with ggez.
