### ISSUE TITLE
Split out layout code into a separate crate

### ISSUE THREAD

**Issue by andrewhickman** [alexheretic/gfx-glyph#36]
Would you consider splitting the layout code (`GlyphPositioner`, `LineBreaker` etc) into a new crate independent of `gfx`? I'm writing a library for text rendering with `vulkano` and I'd rather not reimplement all the layout code, but I also don't want to be depending on `gfx`.

**Comment by alexheretic** [comment]
Yep I think that could work. Actually similar discussion to [rusttype#123](https://gitlab.redox-os.org/redox-os/rusttype/issues/123).

**Comment by andrewhickman** [comment]
Great, I'll have a go at it and create a PR.

**Comment by alexheretic** [comment]
I'm actually having a go myself, so gimme a sec!

**Comment by alexheretic** [comment]
@andrewhickman my plan is to split gfx-glyph into 3:
```
gfx-glyph
└── glyph-brush
    └── glyph-brush-layout
```
[glyph-brush-layout](https://crates.io/crates/glyph_brush_layout) is what you asked for, and should be good to go now. 

[glyph-brush](https://github.com/alexheretic/gfx-glyph/tree/master/glyph-brush) isn't finished yet, currently just the non-gfx bits of gfx-glyph, ie `GlyphCalculator`, that I'm not sure many people use. My plans for it are to move all caching `GlyphBrush` logic into glyph-brush, leaving gfx-glyph with just the gfx specific parts.

Maybe this will be of use to your lib when it's ready?

**Comment by andrewhickman** [comment]
Looks great, thanks!

**Comment by alexheretic** [comment]
I've published the first version of [glyph-brush](https://github.com/alexheretic/gfx-glyph/tree/master/glyph-brush). gfx-glyph master is now just a gfx specific version of this logic. 

Hopefully glyph-brush will apply well to other APIs
